version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: